if: branch = master-jp

sudo: required

language: python

services:
  - docker

before_install:
  - mkdir -p output
  - docker pull htakeuchi/docker-asciidoctor-jp

install:
  - pip install htmldiffer

script:
  - docker run -v $TRAVIS_BUILD_DIR:/documents/ --name asciidoc-to-html htakeuchi/docker-asciidoctor-jp asciidoctor -a allow-uri-read -a data-uri sslrules.adoc
  - docker run -v $TRAVIS_BUILD_DIR:/documents/ --name asciidoc-to-pdf htakeuchi/docker-asciidoctor-jp asciidoctor-pdf -r asciidoctor-pdf-cjk-kai_gen_gothic -a pdf-style=KaiGenGothicJP -a allow-uri-read sslrules.adoc
  - git clone https://${GH_REF} --single-branch --branch gh-pages $TRAVIS_BUILD_DIR/gh-pages
  - cd $TRAVIS_BUILD_DIR/gh-pages
  - cp ../*.html ../*.pdf .
  - python ../diffRules.py ./2022/sslrules.html ./sslrules.html > sslrules-diff.html
  - git config user.name "TravisCI"
  - git config user.email "build-pipeline@travis-ci.org"
  - git add *.html *.pdf
  - git commit -m "Update GitHub Pages"
  - git push "https://${GH_TOKEN}@${GH_REF}" gh-pages
