language: python
os: linux
dist: focal

services:
  - docker

stages:
  - name: build
    if: branch != master-jp
  - name: build-publish
    if: branch = master-jp

jobs:
  include:
    - stage: build
      script:
        - cd $TRAVIS_BUILD_DIR
        - docker run -v $TRAVIS_BUILD_DIR:/documents/ htakeuchi/docker-asciidoctor-jp asciidoctor -r asciidoctor-diagram -a allow-uri-read -a data-uri *.adoc
        - docker run -v $TRAVIS_BUILD_DIR:/documents/ htakeuchi/docker-asciidoctor-jp asciidoctor-pdf -r asciidoctor-diagram  -r asciidoctor-pdf-cjk-kai_gen_gothic -a pdf-style=KaiGenGothicJP -a *.adoc
    - stage: build-publish
      install:
        - pip install htmldiffer
      script:
        - cd $TRAVIS_BUILD_DIR
        - docker run -v $TRAVIS_BUILD_DIR:/documents/ htakeuchi/docker-asciidoctor-jp asciidoctor -r asciidoctor-diagram -a allow-uri-read -a data-uri *.adoc
        - docker run -v $TRAVIS_BUILD_DIR:/documents/ htakeuchi/docker-asciidoctor-jp asciidoctor-pdf -r asciidoctor-diagram  -r asciidoctor-pdf-cjk-kai_gen_gothic -a pdf-style=KaiGenGothicJP -a *.adoc
        - git clone https://${GH_REF} --single-branch --branch gh-pages $TRAVIS_BUILD_DIR/gh-pages
        - cd $TRAVIS_BUILD_DIR/gh-pages
        - cp ../*.html ../*.pdf .
        - year="$(ls -1 | grep -E '^[0-9]{4}$' | sort -n | tail -n1)"
        - python ../diffRules.py ./${year}/sslrules.html ./sslrules.html > sslrules-diff.html
        - git config user.name "TravisCI"
        - git config user.email "build-pipeline@travis-ci.org"
        - git add *.html *.pdf
        - git commit -m "Update GitHub Pages"
        - git push "https://${GH_TOKEN}@${GH_REF}" gh-pages
