[appendix]
== 専門用語/Terminology
=== ボールの操作/Ball Manipulation
シュートと<<ドリブルデバイス/Dribbling Device, ドリブル>>はボールの操作とみなされ、ボールが機体で跳ね返った場合は操作とはみなさない。 +
Shooting and <<ドリブルデバイス/Dribbling Device, dribbling>> is considered as manipulating the ball, the ball accidentally bouncing off the hull is not.

[appendix]
== 試合の状態/Game States

[plantuml, target=game-states, format=svg]
....
@startuml
state Halted {
    state Halt {
    }
    state Timeout {
    }
}

state Stopped {
    state Stop {
    }
    state BallPlacement {
    }
    state PrepareKickoff {
    }
    state PreparePenalty {
    }
}

state Running {
    state Run {
    }
    state FreeKick {
    }
    state Kickoff {
    }
    state Penalty {
    }
}

Halt: Robots are not allowed to move
Timeout: Both teams can do what ever they want
Stop: Both teams have to keep distance to the ball
PrepareKickoff: Teams have to move to their sides
BallPlacement: One team places the ball,\nthe other keeps distance to ball
PreparePenalty: Keeper on goal line,\nattacker behind ball,\nother robots on legal positions
Kickoff: One team may kick the ball\nwithin 5 (A) or 10 (B) seconds
FreeKick: One team may kick the ball\nwithin 5 (A) or 10 (B) seconds
Penalty: Execute a penalty kick within 10 seconds
Run: Both teams may manipulate the ball

[*] -> Halt: (from any state) Halt

Halt --> Stop: Stop
Stop --> Timeout: Timeout
Timeout --> Stop: Stop

Stop --> BallPlacement: Ball Placement
BallPlacement --> Stop: Stop

Stop --> PrepareKickoff: PrepareKickoff
PrepareKickoff --> Kickoff: NormalStart
Kickoff --> Run: after x seconds or if ball moved

Stop --> FreeKick: FreeKick
FreeKick --> Run: after x seconds or if ball moved

Stop --> Run: ForceStart

Stop --> PreparePenalty: PreparePenalty
PreparePenalty --> Penalty: NormalStart
Penalty --> Stop: after 10 seconds
@enduml
....

== ゲームイベント/Game Events
ゲームイベント表は、各ゲームイベントとその結果をまとめたものである。また、<<オートレフ/Automatic Referee, オートレフ>>の実装が処理できなければならないものを表記する。 +
The following game event table is a compilation of the different game events and their consequences. It also lists what all <<オートレフ/Automatic Referee, Automatic Referee>> implementations must be capable of handling.

NOTE: この表にまとめられた情報は不完全なものである。すべての定義を確認するには、対応した各章を読むこと。 +
The information shown in this table here may be incomplete. Please read the sections of the respective events for the full definitions.

[cols="0,1,1,1,1,1"]
|===
|| イベント /Event | 適用範囲 /Applicability | Consequence | Increments Foul Counter | Initiated By

6+| *While Match is Running*
|| <<No Progress In Game>> | <<Ball In And Out Of Play, ball in play>> | <<Stop>> -> <<Force Start>> | no | game controller
|| <<Double Touch>> | <<Ball In And Out Of Play, ball in play>> | <<Stop>> -> <<Free Kick>> | no | auto referee

| 5+| *Ball Leaving the Field*
|| <<Scoring Goals, Possible Goal>> | <<Ball In And Out Of Play, ball in play>> | <<Halt>> | no | auto referee
|| <<Touch Line Crossing>> | <<Ball In And Out Of Play, ball in play>> | <<Stop>> -> <<Free Kick>> | no | auto referee
|| <<Goal Line Crossing>> | <<Ball In And Out Of Play, ball in play>> | <<Stop>> -> <<Free Kick>> | no | auto referee
|| <<aimless-kick, Aimless Kick>> | <<Ball In And Out Of Play, ball in play>> | <<Stop>> -> <<Free Kick>> | no | auto referee

| 5+| *Fouls*
|| <<Multiple Defenders>> | <<Ball In And Out Of Play, ball in play>> | <<Stop>> -> <<Penalty Kick>> | no | auto referee
|| <<Keeper Held Ball>> in <<Defense Area, defense area>> | <<Ball In And Out Of Play, ball in play>> | <<Stop>> -> <<Free Kick>> | yes | game controller
|| <<Boundary Crossing>> | <<Ball In And Out Of Play, ball in play>> | <<Stop>> -> <<Free Kick>> | yes | auto referee
|| <<Excessive Dribbling>> | <<Ball In And Out Of Play, ball in play>> | <<Stop>> -> <<Free Kick>> | yes | auto referee
|| <<Attacker Touched Ball In Opponent Defense Area>> | <<Ball In And Out Of Play, ball in play>> | - | yes | auto referee
|| <<Ball Speed>> | <<Ball In And Out Of Play, ball in play>> | - | yes | auto referee

| 5+| *Penalty Kick*
|| <<Penalty Kick>> failed | during <<Penalty Kick>> | <<Stop>> -> <<Free Kick>> | no | auto referee, game controller

6+| *Always*
|| <<Crashing>> | always | - | yes | auto referee
|| <<Crashing>> draw | always | - | yes | auto referee

6+| *During Free Kick and While Match is Stop*
|| <<Robot Too Close To Opponent Defense Area>> | during <<Stop>> and <<Free Kick>> | <<Stop>> -> <<Free Kick>> | yes | auto referee

6+| *While Match is Stopped*

| 5+| *Fouls*
|| <<Robot Stop Speed>> | during <<Stop>> | - | yes | auto referee
|| <<Defender Too Close To Ball>> | <<Ball In And Out Of Play, ball out of play>> | timer for bringing the ball into play is reset | yes | auto referee

| 5+| *Ball Placement*
|| <<Ball Placement Interference>> | during <<Ball Placement>> | placement timer increased by 10 seconds | no | auto referee
|| <<Ball Placement>> successful | during <<Ball Placement>> | continue | no | auto referee
|| <<Ball Placement>> failed by team in favor | during <<Ball Placement>> | <<Stop>> -> <<Free Kick>> (div A) / previous command (div B) | no | game controller
|| <<Ball Placement>> failed by opponent | during <<Ball Placement>> | <<Stop>> | no | game controller

6+| *Informational*
|| Multiple <<Fouls>> | - | <<Yellow Card>> | no | game controller
|| Multiple <<Yellow Card, Yellow Cards>> | - | <<Red Card>> | no | game controller
|| <<Number Of Robots>> exceeded | - | <<Stop>> | no | game controller
|| <<Scoring Goals, Invalid Goal>> | - | <<Stop>> -> <<Free Kick>> | no | game controller
|| Perform manual <<Robot Substitution>> | during <<Stop>> | <<Halt>> (after next stoppage), then <<Stop>> | no | remote control
|| Raise <<Challenge Flags, Challenge flag>> | always | - | no | remote control
|| Perform <<Emergency stop>> | always | <<Halt>> | no | remote control

6+| *Manual*
|| <<Scoring Goals, Goal>> | - | <<Stop>> -> <<Kick-Off>> | no | human referee
|| <<Pushing>> | always | <<Stop>> -> <<Free Kick>> | yes | human referee
|| <<Ball Holding>> | <<Ball In And Out Of Play, ball in play>> | <<Stop>> -> <<Free Kick>> | yes | human referee
|| <<Tipping Over Or Dropping Parts>> | always | <<Stop>> -> <<Free Kick>> | yes | human referee
|| <<Unsporting Behavior, Minor Unsporting Behavior>> | always | <<Stop>> -> <<Yellow Card>> | no | human referee
|| <<Unsporting Behavior, Major Unsporting Behavior>> | always | <<Stop>> -> <<Red Card>> | no | human referee
|===

NOTE: (訳者注記) 「リモートコントロール」は大会運営者により提供され、ソフトウェアではなく物理的な旗、その他何らかのデバイスである可能性もある。詳細は<<コミュニケーションフラッグ/Communication Flags, コミュニケーションフラッグに関するルール>>を参照すること。 +

[appendix]
== 各種時間の概要/Overview of Timings
|===
| 状況/Situation | ディヴィジョンAの時間/Div A Time | ディヴィジョンBの時間/Div B Time

| <<イエローカード/Yellow Card, イエローカード>>によるロボット除去 +
Remove robot for <<イエローカード/Yellow Card, Yellow Card>>
| 10 s       | 10 s

| <<ペナルティーキック/Penalty Kick, ペナルティーキック>> +
<<ペナルティーキック/Penalty Kick, penalty kick>>
| 10 s       | 10 s

| <<キックオフ/Kick-Off, キックオフ>> +
<<キックオフ/Kick-Off, kick-off>>
| 10 s       | 10 s

| <<フリーキック/Free Kick, フリーキック>> +
<<フリーキック/Free Kick, free kick>>
|  5 s       | 10 s

| <<ディフェンスエリア/Defense Area, ディフェンスエリア>>内での<<キーパーによるボール保持/Keeper Held Ball, キーパーによるボール保持>> +
<<キーパーによるボール保持/Keeper Held Ball, Keeper Held Ball>> inside <<ディフェンスエリア/Defense Area, Defense Area>>
|  5 s       | 10 s

| <<試合の停滞/No Progress In Game, 試合の停滞>> +
<<試合の停滞/No Progress In Game, No Progress In Game>>
|  5 s       | 10 s
|===


[appendix]
== ディヴィジョンごとの違い/Differences Between Divisions

これは、<<ディヴィジョン/Divisions, ディヴィジョン>>Aと<<ディヴィジョン/Divisions, ディヴィジョン>>Bの違いの完全なリストである。 +
This is a complete list of differences between <<ディヴィジョン/Divisions, division>> A and <<ディヴィジョン/Divisions, division>> B.

* ディヴィジョンAはディヴィジョンBよりも<<フィールドの大きさ/Dimensions, 大きなフィールド>>と<<ゴール/Goals, 大きなゴール>>で試合を行う。その結果、<<ペナルティーキック/Penalty Kick, ペナルティーキック>>もより遠くから行われる。 +
Division A plays on a <<フィールドの大きさ/Dimensions, larger field>> with <<ゴール/Goals, larger goals>> than division B. As a result, the <<ペナルティーキック/Penalty Kick, penalty kick>> is taken from a greater distance as well.
* ディヴィジョンAはディヴィジョンBよりも<<ロボットの台数/Number Of Robots, 多いロボット>>で試合を行う。 +
Division A plays with <<ロボットの台数/Number Of Robots, more robots>> than division B.
* <<ボール配置/Ball Placement, ボール配置>>の手順はディヴィジョンAでは必須であり、ディヴィジョンBでは任意である。 +
The automatic <<ボール配置/Ball Placement, ball placement>> procedure is mandatory for division A and optional for division B.
* <<aimless-kick, エイムレスキック>>のルールはディヴィジョンBにのみ適用される。 +
The <<aimless-kick, aimless kick>> rule only applies to division B.
* ディヴィジョンAはいくつかの状況における時間切れまでの時間が短い。 +
Division A has shorter timeouts in some situations
* <<非常停止/Emergency stop, 非常停止>>はディヴィジョンAにのみ適用される。 +
<<非常停止/Emergency stop, Emergency stop>> only applies to division A.
