[appendix]
== 専門用語/Terminology
=== ボールの操作/Ball Manipulation
シュートと<<ドリブルデバイス/Dribbling Device, ドリブル>>はボールの操作とみなされ、ボールが機体で跳ね返った場合は操作とはみなさない。 +
Shooting and <<ドリブルデバイス/Dribbling Device, dribbling>> is considered as manipulating the ball, the ball accidentally bouncing off the hull is not.

[appendix]
== 試合の状態/Game States

[plantuml, target=game-states, format=svg]
....
@startuml
state Halted {
    state Halt {
    }
    state Timeout {
    }
}

state Stopped {
    state Stop {
    }
    state BallPlacement {
    }
    state PrepareKickoff {
    }
    state PreparePenalty {
    }
}

state Running {
    state Run {
    }
    state FreeKick {
    }
    state Kickoff {
    }
    state Penalty {
    }
}

Halt: Robots are not allowed to move
Timeout: Both teams can do what ever they want
Stop: Both teams have to keep distance to the ball
PrepareKickoff: Teams have to move to their sides
BallPlacement: One team places the ball,\nthe other keeps distance to ball
PreparePenalty: Keeper on goal line,\nattacker behind ball,\nother robots on legal positions
Kickoff: One team may kick the ball\nwithin 5 (A) or 10 (B) seconds
FreeKick: One team may kick the ball\nwithin 5 (A) or 10 (B) seconds
Penalty: Execute a penalty kick within 10 seconds
Run: Both teams may manipulate the ball

[*] -> Halt: (from any state) Halt

Halt --> Stop: Stop
Stop --> Timeout: Timeout
Timeout --> Stop: Stop

Stop --> BallPlacement: Ball Placement
BallPlacement --> Stop: Stop
BallPlacement --> FreeKick: Continue

Stop --> PrepareKickoff: PrepareKickoff
PrepareKickoff --> Kickoff: NormalStart
Kickoff --> Run: after x seconds or if ball moved

Stop --> FreeKick: FreeKick
FreeKick --> Run: after x seconds or if ball moved

Stop --> Run: ForceStart

Stop --> PreparePenalty: PreparePenalty
PreparePenalty --> Penalty: NormalStart
Penalty --> Stop: after 10 seconds

Run --> Stop: Stop
@enduml
....

== ゲームイベント/Game Events
次に示すゲームイベント表は、各ゲームイベントとその結果をまとめたものである。また、<<オートレフ/Automatic Referee, オートレフ>>の実装が処理できなければならないものを表記する。 +
The following game event table is a compilation of the different game events and their consequences. It also lists what all <<オートレフ/Automatic Referee, Automatic Referee>> implementations must be capable of handling.

NOTE: この表にまとめられた情報は不完全なものである可能性がある。すべての定義を確認するには、対応した各章を読むこと。 +
The information shown in this table here may be incomplete. Please read the sections of the respective events for the full definitions.

[cols="0,1,1,1,1,1"]
|===
|| イベント/Event | 適用範囲/Applicability | 結果/Consequence | ファウル回数カウンターへの計上/Increments Foul Counter | 始点/Initiated By

6+| *インプレイ中/While Match is Running*
|| <<試合の停滞/No Progress In Game, NO_PROGRESS_IN_GAME>> | <<インプレイとアウトオブプレイ/Ball In And Out Of Play, ball in play>> | <<停止/Stop>> -> <<フォーススタート/Force Start>> | no | game controller
|| <<ダブルタッチ/Double Touch, ATTACKER_DOUBLE_TOUCHED_BALL>> | <<インプレイとアウトオブプレイ/Ball In And Out Of Play, ball in play>> | <<停止/Stop>> -> <<フリーキック/Free Kick>> | no | auto referee

| 5+| *ボールがフィールド外に出た時/Ball Leaving the Field*
|| <<得点/Scoring Goals, POSSIBLE_GOAL>> | <<インプレイとアウトオブプレイ/Ball In And Out Of Play, ball in play>> | <<ハルト/Halt>> | no | auto referee
|| <<タッチラインとの交差/Touch Line Crossing, BALL_LEFT_FIELD_TOUCH_LINE>> | <<インプレイとアウトオブプレイ/Ball In And Out Of Play, ball in play>> | <<停止/Stop>> -> <<フリーキック/Free Kick>> | no | auto referee
|| <<ゴールラインとの交差/Goal Line Crossing, BALL_LEFT_FIELD_GOAL_LINE>> | <<インプレイとアウトオブプレイ/Ball In And Out Of Play, ball in play>> | <<停止/Stop>> -> <<フリーキック/Free Kick>> | no | auto referee
|| <<aimless-kick, AIMLESS_KICK>> | <<インプレイとアウトオブプレイ/Ball In And Out Of Play, ball in play>> | <<停止/Stop>> -> <<フリーキック/Free Kick>> | no | auto referee

| 5+| *ファウル/Fouls*
|| <<マルチプルディフェンス/Multiple Defenders, DEFENDER_IN_DEFENSE_AREA>> | <<インプレイとアウトオブプレイ/Ball In And Out Of Play, ball in play>> | <<停止/Stop>> -> <<ペナルティーキック/Penalty Kick>> | no | auto referee
|| <<キーパーによるボール保持/Keeper Held Ball, KEEPER_HELD_BALL>> | <<インプレイとアウトオブプレイ/Ball In And Out Of Play, ball in play>> | <<停止/Stop>> -> <<フリーキック/Free Kick>> | yes | game controller
|| <<境界線との交差/Boundary Crossing, BOUNDARY_CROSSING>> | <<インプレイとアウトオブプレイ/Ball In And Out Of Play, ball in play>> | <<停止/Stop>> -> <<フリーキック/Free Kick>> | yes | auto referee
|| <<ドリブルの超過/Excessive Dribbling, BOT_DRIBBLED_BALL_TOO_FAR>> | <<インプレイとアウトオブプレイ/Ball In And Out Of Play, ball in play>> | <<停止/Stop>> -> <<フリーキック/Free Kick>> | yes | auto referee
|| <<相手ディフェンスエリア内でのアタッカーのボールへの接触/Attacker Touched Ball In Opponent Defense Area, ATTACKER_TOUCHED_BALL_IN_DEFENSE_AREA>> | <<インプレイとアウトオブプレイ/Ball In And Out Of Play, ball in play>> | - | yes | auto referee
|| <<ボール速度/Ball Speed, BOT_KICKED_BALL_TOO_FAST>> | <<インプレイとアウトオブプレイ/Ball In And Out Of Play, ball in play>> | - | yes | auto referee

| 5+| *ペナルティーキック/Penalty Kick*
|| <<ペナルティーキック/Penalty Kick, PENALTY_KICK_FAILED>>
| <<ペナルティーキック/Penalty Kick, ペナルティーキック>>中 +
during <<ペナルティーキック/Penalty Kick, Penalty Kick>>
| <<停止/Stop>> -> <<フリーキック/Free Kick>> | no | auto referee, game controller

6+| *常時/always*
|| <<衝突/Crashing, BOT_CRASH_UNIQUE>> | 常時/always | - | yes | auto referee
|| <<衝突/Crashing, BOT_CRASH_DRAWN>> | 常時/always | - | yes | auto referee

6+| *フリーキックおよびストップゲーム中/During Free Kick and While Match is Stop*
|| <<ロボットの相手ディフェンスエリアへの極端な接近/Robot Too Close To Opponent Defense Area, ATTACKER_TOO_CLOSE_TO_DEFENSE_AREA>>
| <<停止/Stop, ストップ>>中および<<フリーキック/Free Kick, フリーキック>>中 + 
during <<停止/Stop, Stop>> and <<フリーキック/Free Kick, Free Kick>> 
| <<停止/Stop>> -> <<フリーキック/Free Kick>> | yes | auto referee

6+| *ストップゲーム中/While Match is Stopped*

| 5+| *ファウル/Fouls*
|| <<ストップ中のロボットの速度/Robot Stop Speed, BOT_TOO_FAST_IN_STOP>> 
| <<停止/Stop, ストップ>>中 +
during <<停止/Stop, Stop>>
| - | yes | auto referee

|| <<ディフェンダーのボールへの極端な接近/Defender Too Close To Ball, DEFENDER_TOO_CLOSE_TO_KICK_POINT>> 
| <<インプレイとアウトオブプレイ/Ball In And Out Of Play, アウトオブプレイ中>> +
<<インプレイとアウトオブプレイ/Ball In And Out Of Play, ball out of play>> 
| インプレイにするまでの時間制限のタイマーをリセット +
timer for bringing the ball into play is reset
| yes | auto referee

| 5+| *ボール配置/Ball Placement*
|| <<ボール配置への干渉/Ball Placement Interference, BOT_INTERFERED_PLACEMENT>> 
| <<ボール配置/Ball Placement, ボール配置>>中 +
during <<ボール配置/Ball Placement, Ball Placement>>
| 配置制限時間のタイマーを10秒延長 +
placement timer increased by 10 seconds
| yes | auto referee
|| <<ボール配置/Ball Placement, PLACEMENT_SUCCEEDED>>
| <<ボール配置/Ball Placement, ボール配置>>中 +
during <<ボール配置/Ball Placement, Ball Placement>>
| 続行 +
continue 
| no | auto referee
|| <<ボール配置/Ball Placement, PLACEMENT_FAILED>> by team in favor 
| <<ボール配置/Ball Placement, ボール配置>>中 +
during <<ボール配置/Ball Placement, Ball Placement>>
| <<停止/Stop>> -> <<フリーキック/Free Kick>> (div A) / previous command (div B) | no | game controller
|| <<ボール配置/Ball Placement, PLACEMENT_FAILED>> by opponent 
| <<ボール配置/Ball Placement, ボール配置>>中 +
during <<ボール配置/Ball Placement, Ball Placement>>
| <<停止/Stop>> | no | game controller

6+| *Informational*
|| <<ファウル/Fouls, MULTIPLE_FOULS>> | - | <<イエローカード/Yellow Card>> | no | game controller
|| <<イエローカード/Yellow Card, MULTIPLE_CARDS>> | - | <<レッドカード/Red Card>> | no | game controller
|| <<ロボットの台数/Number Of Robots, TOO_MANY_ROBOTS>> | - | <<停止/Stop>> | no | game controller
|| <<得点/Scoring Goals, INVALID_GOAL>> | - | <<停止/Stop>> -> <<フリーキック/Free Kick>> | no | game controller
|| <<ロボットの交代/Robot Substitution, BOT_SUBSTITUTION>> 
| <<停止/Stop, 停止>>中 +
during <<停止/Stop, Stop>>
| (次の停止時に)<<ハルト/Halt, ハルト>>、次いで<<停止/Stop, 停止>> +
<<ハルト/Halt, Halt>> (after next stoppage), then <<停止/Stop, Stop>> | no | remote control
|| <<チャレンジフラッグ/Challenge Flags, CHALLENGE_FLAG>> | 常時/always | - | no | remote control
|| <<非常停止/Emergency stop, EMERGENCY_STOP>> | 常時/always | <<ハルト/Halt>> -> <<タイムアウト/Timeouts, Timeout>> + <<イエローカード/Yellow Card>>>> | no | remote control

6+| *手動/Manual*
|| <<得点/Scoring Goals, GOAL>> | - | <<停止/Stop>> -> <<キックオフ/Kick-Off>> | no | human referee
|| <<プッシング/Pushing, BOT_PUSHED_BOT>> | 常時/always | <<停止/Stop>> -> <<フリーキック/Free Kick>> | yes | human referee
|| <<ボールの保持/Ball Holding, BOT_HELD_BALL_DELIBERATELY>> | <<インプレイとアウトオブプレイ/Ball In And Out Of Play, ball in play>> | <<停止/Stop>> -> <<フリーキック/Free Kick>> | yes | human referee
|| <<転倒や部品の脱落/Tipping Over Or Dropping Parts, BOT_TIPPED_OVER>> | 常時/always | <<停止/Stop>> -> <<フリーキック/Free Kick>> | yes | human referee
|| <<非スポーツマン行為/Unsporting Behavior, UNSPORTING_BEHAVIOR_MINOR>> | 常時/always | <<停止/Stop>> -> <<イエローカード/Yellow Card>>>> | no | human referee
|| <<非スポーツマン行為/Unsporting Behavior,UNSPORTING_BEHAVIOR_MAJOR>> | 常時/always | <<停止/Stop>> -> <<レッドカード/Red Card>> | no | human referee
|===

NOTE: (訳者注記) 「リモートコントロール」は大会運営者により提供され、ソフトウェアではなく物理的な旗、その他何らかのデバイスである可能性もある。詳細は<<コミュニケーションフラッグ/Communication Flags, コミュニケーションフラッグに関するルール>>を参照すること。 +

[appendix]
== 各種時間の概要/Overview of Timings
|===
| 状況/Situation | ディヴィジョンAの時間/Div A Time | ディヴィジョンBの時間/Div B Time

| <<イエローカード/Yellow Card, イエローカード>>によるロボット除去 +
Remove robot for <<イエローカード/Yellow Card, Yellow Card>>
| 10 s       | 10 s

| <<ペナルティーキック/Penalty Kick, ペナルティーキック>> +
<<ペナルティーキック/Penalty Kick, penalty kick>>
| 10 s       | 10 s

| <<キックオフ/Kick-Off, キックオフ>> +
<<キックオフ/Kick-Off, kick-off>>
| 10 s       | 10 s

| <<フリーキック/Free Kick, フリーキック>> +
<<フリーキック/Free Kick, free kick>>
|  5 s       | 10 s

| <<ディフェンスエリア/Defense Area, ディフェンスエリア>>内での<<キーパーによるボール保持/Keeper Held Ball, キーパーによるボール保持>> +
<<キーパーによるボール保持/Keeper Held Ball, Keeper Held Ball>> inside <<ディフェンスエリア/Defense Area, Defense Area>>
|  5 s       | 10 s

| <<試合の停滞/No Progress In Game, 試合の停滞>> +
<<試合の停滞/No Progress In Game, No Progress In Game>>
|  5 s       | 10 s
|===

https://raw.githubusercontent.com/RoboCup-SSL/ssl-rules/master/images/SSL_Game_Events.graphml[graphml] 形式で記載されたゲームイベントの図を https://www.yworks.com/yed-live/?file=https://raw.githubusercontent.com/RoboCup-SSL/ssl-rules/master/images/SSL_Game_Events.graphml[yed-live] のページから閲覧できる。 +
A visualized graph of the game events is stored as https://raw.githubusercontent.com/RoboCup-SSL/ssl-rules/master/images/SSL_Game_Events.graphml[graphml] and can be viewed at https://www.yworks.com/yed-live/?file=https://raw.githubusercontent.com/RoboCup-SSL/ssl-rules/master/images/SSL_Game_Events.graphml[yed-live].

[appendix]
== ディヴィジョンごとの違い/Differences Between Divisions

これは、<<ディヴィジョン/Divisions, ディヴィジョン>>Aと<<ディヴィジョン/Divisions, ディヴィジョン>>Bの違いの完全なリストである。 +
This is a complete list of differences between <<ディヴィジョン/Divisions, division>> A and <<ディヴィジョン/Divisions, division>> B.

* ディヴィジョンAはディヴィジョンBよりも<<フィールドの大きさ/Dimensions, 大きなフィールド>>と<<ゴール/Goals, 大きなゴール>>で試合を行う。その結果、<<ペナルティーキック/Penalty Kick, ペナルティーキック>>もより遠くから行われる。 +
Division A plays on a <<フィールドの大きさ/Dimensions, larger field>> with <<ゴール/Goals, larger goals>> than division B. As a result, the <<ペナルティーキック/Penalty Kick, penalty kick>> is taken from a greater distance as well.
* ディヴィジョンAはディヴィジョンBよりも<<ロボットの台数/Number Of Robots, 多いロボット>>で試合を行う。 +
Division A plays with <<ロボットの台数/Number Of Robots, more robots>> than division B.
* <<ボール配置/Ball Placement, ボール配置>>の手順はディヴィジョンAでは必須であり、ディヴィジョンBでは任意である。 +
The automatic <<ボール配置/Ball Placement, ball placement>> procedure is mandatory for division A and optional for division B.
* <<aimless-kick, エイムレスキック>>のルールはディヴィジョンBにのみ適用される。 +
The <<aimless-kick, aimless kick>> rule only applies to division B.
* ディヴィジョンAはいくつかの状況における時間切れまでの時間が短い。 +
Division A has shorter timeouts in some situations
